# Generated by Django 6.0.6 on 2026-06-24 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currencyId', models.AutoField(primary_key=True, serialize=False)),
                ('currencyName', models.CharField(blank=True, max_length=100, null=True)),
                ('currencyCode', models.CharField(blank=True, max_length=100, null=True)),
                ('currencySymbol', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessConfig',
            fields=[
                ('processConfigId', models.AutoField(primary_key=True, serialize=False)),
                ('processCode', models.CharField(max_length=100)),
                ('sellerShipperDeliveryFee', models.FloatField(blank=True, null=True)),
                ('sellerShipperDeliveryFeeUnit', models.CharField(blank=True, max_length=100, null=True)),
                ('handlingFee', models.FloatField(blank=True, null=True)),
                ('handlingFeeUnit', models.CharField(blank=True, max_length=100, null=True)),
                ('weightUnit', models.CharField(blank=True, max_length=100, null=True)),
                ('shippingMode', models.CharField(blank=True, max_length=100, null=True)),
                ('customRate', models.FloatField(blank=True, null=True)),
                ('customRateUnit', models.CharField(blank=True, max_length=100, null=True)),
                ('shippingMargin', models.FloatField(blank=True, null=True)),
                ('shippingMarginUnit', models.CharField(blank=True, max_length=100, null=True)),
                ('defaultCurrency', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receiptId', models.AutoField(primary_key=True, serialize=False)),
                ('receiptCode', models.CharField(max_length=100)),
                ('receiptName', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemUnits',
            fields=[
                ('systemUnitId', models.AutoField(primary_key=True, serialize=False)),
                ('unitName', models.CharField(blank=True, max_length=100, null=True)),
                ('unitCode', models.CharField(blank=True, max_length=100, null=True)),
                ('unitSymbol', models.CharField(blank=True, max_length=100, null=True)),
                ('unitDescription', models.TextField(blank=True, null=True)),
                ('unitType', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FX',
            fields=[
                ('fxId', models.AutoField(primary_key=True, serialize=False)),
                ('exchangeRate', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiveCurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_to_currency', to='eezy_source.currency')),
                ('sendCurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_from_currency', to='eezy_source.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('recordId', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=40)),
                ('itemCost', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('totalCost', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.SmallIntegerField(blank=True, null=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_receipt', to='eezy_source.receipt')),
            ],
        ),
    ]
