# Generated by Django 6.0.6 on 2026-07-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eezy_source', '0002_business_user_record_deliveryfee_record_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
